---
title: "Bertens Validation"
author: "Amin Adibi"
date: "23/03/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Validation

```{r dataprep, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(bertens)
library(pROC)
library(gbm)
library(rmda)
library(ggthemes)
library(naniar)
eclipse.raw <- read_csv("eclipse.csv") %>% 
  filter (VISIT == "1 Year") %>% 
  select (id = SUBJECT_ID, Age = AGE, sex = SEX, 
          fev1 = FEV1PSPC) %>%
          mutate(id = str_remove(id, "xyl"))

# better cardiovascular data also available.

packyear <- read_table2("packyear.txt") %>% select (id = SUBJECT_ID, packyears = SUPKYR) %>%
                                            mutate(id = str_remove(id, "ecl"))

cv_cond <- read_csv("cv_cond.csv") %>% select (id= SUBJECT_ID, 
                                               strokeHx = ATS8E,
                                               heartAttackHx = ATS8D) %>%
                                       mutate(id = str_remove(id, "xyl"))


exacerbation <- read_csv("exacerbation.csv") %>% select(id= SUBJECT_ID, 
                                                        year = YRCAT,
                                                        modSevereExac = EXACNUM1,
                                                        sevExac = SEVEXN1) %>%
                                                        #followup = OBSTIME) %>%
               pivot_wider(names_from = year, values_from = c(modSevereExac, sevExac)) %>%
               mutate(year1 = `modSevereExac_Year 1`,
                      year2 = `modSevereExac_Year 2`,
                      year2to3 = `modSevereExac_Years 1-3` - year1,
                      year1Sev = `sevExac_Year 1`,
                      id = str_remove(id, "xyl")) %>%
               select (id, year1, year1Sev, year2, year2to3)


# the paper defines A history of vascular disease was defined as stroke, transient ischemic attack, or peripheral arterial disease.
# we used strokeHx | heartAttackHx as a proxy for it in ECLIPSE.
eclipse <- eclipse.raw %>% filter (fev1<85) %>%  # removing non-copd controls
                           left_join(cv_cond, by = "id") %>% left_join(packyear, by = "id") %>%
                           mutate(strokeHx  = recode (strokeHx,
                                                      "Y" = "TRUE",
                                                      "N" = "FALSE",
                                                      "U" = "NA")) %>%
                           mutate(heartAttackHx  = recode (heartAttackHx,
                                                      "Y" = "TRUE",
                                                      "N" = "FALSE")) %>%
                           mutate(heartAttackHx = as.logical(heartAttackHx),
                                  strokeHx = as.logical(strokeHx),
                                  vascularDx = (strokeHx | heartAttackHx)) %>%
                          select(-strokeHx, -heartAttackHx) %>%
                          left_join(exacerbation, by = "id") %>%
                        #  filter(packyears > 0) %>%
                          mutate(Observed_Exac_in2to3 = ifelse(year2to3>0, 1, 0))  %>%
                          mutate(Observed_Exac_in2 = ifelse(year2>0, 1, 0))  %>%
                          mutate(year1FreqExacerbator = ifelse(((year1>1) | (year1Sev>0)), 1, 0),
                                 year1HadExac = ifelse(year1>0, 1, 0),
                                 predictedBertens = 
                                   bertens(exacerbationHx = year1HadExac, 
                                           fev1=fev1, 
                                           packYears = packyears,
                                           vascularDx = vascularDx),
                                 predictedBertens1Yr = 1-sqrt(1-predictedBertens)) 

eclipseComplete <- eclipse %>% drop_na()

eclipseCompleteSmokers <- eclipseComplete %>% filter (packyears>=1)

write.csv(eclipse, "eclipse_bertens.csv")

```

### Missing Values
```{r missingData, echo=FALSE}
#missing data
eclipse %>% gg_miss_fct(fct = sex) + xlab ("") + ylab("") + theme(legend.position="top")

eclipseComplete %>% head()
```
<!-- ### Data Summary -->
<!-- ```{r dataSummary, echo=FALSE} -->

<!-- ggplot_density <- function(dataset, group, VarName, Height = px(50), PaletteName = "Set1") { -->
<!-- # force(VarName) -->
<!--   if (is.null(group)) { -->
<!--     gg_object <- ggplot(data = dataset, aes(x = !!sym(VarName), fill = 1)) + -->
<!--       geom_density(alpha = 0.4) + -->
<!--       scale_fill_brewer(palette = PaletteName) + -->
<!--       theme_classic() + -->
<!--       scale_x_continuous(breaks = breaks_pretty(3)) + -->
<!--       theme(axis.title = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), -->
<!--             axis.line.y = element_blank(), text = element_text(size = 80), legend.position="none") -->
<!--   } -->
<!--   else { -->
<!--     gg_object <- ggplot(data = dataset, aes(x = !!sym(VarName), fill = !!sym(group))) + -->
<!--       geom_density(alpha = 0.4) + -->
<!--       scale_fill_brewer(palette = PaletteName) + -->
<!--       # scale_fill_manual(values = color_list) + -->
<!--       theme_classic() + -->
<!--       scale_x_continuous(breaks = breaks_pretty(3)) + -->
<!--       theme(axis.title = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), -->
<!--             axis.line.y = element_blank(), text = element_text(size = 80), legend.position="none") -->
<!--   } -->
<!--   gg_object %>% ggplot_image(height = Height) -->
<!-- } -->


<!-- ggplot_bar <- function(dataset, group, VarName, Height = px(50), PaletteName = "Set1") { -->
<!--   if (is.null(group)) { -->
<!--     gg_object = ggplot(data = dataset, aes(x = !!sym(VarName), fill = 1)) + -->
<!--       geom_bar(stat = "count", width = 0.5, position = position_dodge(width = 0.9)) + -->
<!--       scale_fill_brewer(palette = PaletteName) + -->
<!--       theme_classic() + -->
<!--       theme(axis.title = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), -->
<!--             axis.line.y = element_blank(), text = element_text(size = 65), legend.position="none") -->
<!--   } -->
<!--   else { -->
<!--     gg_object = ggplot(data = dataset, aes(x = !!sym(VarName), fill = !!sym(group))) + -->
<!--       geom_bar(stat = "count", width = 0.5, position = position_dodge(width = 0.9)) + -->
<!--       scale_fill_brewer(palette = "Set1") + -->
<!--       # scale_fill_manual(values = color_list) + -->
<!--       theme_classic() + -->
<!--       theme(axis.title = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), -->
<!--             axis.line.y = element_blank(), text = element_text(size = 65), legend.position="none") -->
<!--   } -->
<!--   gg_object %>% ggplot_image(height = Height) -->
<!-- } -->

<!-- ## Covariates summary statistics -->
<!-- n_decimal <- 1 -->
<!-- n_group <- length(table(eclipseComplete[ , "group"])) -->
<!-- # color_list <- c("#4285F4", "#EA4335", "#34A853", "#FBBC05", "purple")[c(1 : n_group)] -->
<!-- ContVarList <- c("Age", "fev1", "packyears", "SGRQ") -->
<!-- OutcVarList <- c("year2to3") -->
<!-- CatVarList <- c("sex", "year1HadExac", "vascularDx") -->
<!-- col_names <- names(table(eclipseComplete[ , "group"])) -->
<!-- eclipseComplete %>% -->
<!--   group_by(group) %>% -->
<!--   summarise(n = n(), -->
<!--             Predictors = "Mean (SD)", -->
<!--             `Age (year)` = paste0(round(mean(`Age (year)`), digits = n_decimal), -->
<!--                                   " (", round(sd(`Age (year)`), digits = n_decimal), ")"), -->
<!--             `FEV1 % Predicted` = paste0(round(mean(`FEV1 % Predicted`), digits = n_decimal), -->
<!--                                         " (", round(sd(`FEV1 % Predicted`), digits = n_decimal), ")"), -->
<!--             `BMI` = paste0(round(mean(`BMI`), digits = n_decimal), -->
<!--                            " (", round(sd(`BMI`), digits = n_decimal), ")"), -->
<!--             `SGRQ` = paste0(round(mean(`SGRQ`, na.rm = T), digits = n_decimal), -->
<!--                             " (", round(sd(`SGRQ`, na.rm = T), digits = n_decimal), ")"), -->
<!--             temp1 = "Count (%)", -->
<!--             `Sex (male)` = paste0(sum(`Sex (male)` == "Male"), -->
<!--                                   " (", round(100 * mean(`Sex (male)` == "Male"), digits = n_decimal), "%)"), -->
<!--             `Current smoker` = paste0(sum(`Current smoker` == "Yes"), -->
<!--                                       " (", round(100 * mean(`Current smoker` == "Yes"), digits = n_decimal), "%)"), -->
<!--             `On statin` = paste0(sum(`On statin` == "Yes"), -->
<!--                                  " (", round(100 * mean(`On statin` == "Yes"), digits = n_decimal), "%)"), -->
<!--             `O2 therapy` = paste0(sum(`O2 therapy` == "Yes"), -->
<!--                                   " (", round(100 * mean(`O2 therapy` == "Yes"), digits = n_decimal), "%)"), -->
<!--             `On LAMA` = paste0(sum(`On LAMA` == "Yes"), -->
<!--                                " (", round(100 * mean(`On LAMA` == "Yes"), digits = n_decimal), "%)"), -->
<!--             `On LABA` = paste0(sum(`On LABA` == "Yes"), -->
<!--                                " (", round(100 * mean(`On LABA` == "Yes"), digits = n_decimal), "%)"), -->
<!--             `On ICS` = paste0(sum(`On ICS` == "Yes"), -->
<!--                               " (", round(100 * mean(`On ICS` == "Yes"), digits = n_decimal), "%)"), -->
<!--             Outcomes = "Count (Rate)", -->
<!--             `Follow-up time (year)` = paste0(round(mean(YIS), digits = 2), -->
<!--                                              " (", round(sd(YIS), digits = n_decimal), ")"), -->
<!--             `All exacerbations` = paste0(sum(obsExac), -->
<!--                                                        " (", round(sum(obsExac) / sum(YIS), digits = 2), ")"), -->
<!--             `Severe exacerbations` = paste0(sum(obsExac_Sev), -->
<!--                                                        " (", round(sum(obsExac_Sev) / sum(YIS), digits = 2), ")")) -> DataSummary_temp -->
<!-- DataSummary_temp_t <- t(DataSummary_temp[ , -1]) -->
<!-- colnames(DataSummary_temp_t) <- levels(as.data.frame(DataSummary_temp)[ , 1]) -->
<!-- DataSummary <- as.data.frame(DataSummary_temp_t) -->
<!-- DataSummary[c("Predictors", "temp1", "Outcomes") , c("Development Sample", "TORCH")] <- "" -->
<!-- rownames(DataSummary)[grep("temp", rownames(DataSummary))] <- c("") -->
<!-- DataSummary$Distribution <- NA -->
<!-- ContVarList_gg <- NULL -->
<!-- for (varTemp in ContVarList) { -->
<!--   ContVarList_gg <- c(ContVarList_gg, -->
<!--                       ggplot_density(dataset = AllTrials_Data_Table1_temp, group = "group", VarName = varTemp, -->
<!--                                      Height = px(50))) -->
<!-- } -->
<!-- OutcVarList_gg <- NULL -->
<!-- for (varTemp in OutcVarList) { -->
<!--   OutcVarList_gg <- c(OutcVarList_gg, -->
<!--                       ggplot_density(dataset = AllTrials_Data_Table1_temp, group = "group", VarName = varTemp, -->
<!--                                      Height = px(50))) -->
<!-- } -->
<!-- CatVarList_gg <- NULL -->
<!-- for (varTemp in CatVarList) { -->
<!--   CatVarList_gg <- c(CatVarList_gg, -->
<!--                      ggplot_bar(dataset = AllTrials_Data_Table1_temp, group = "group", VarName = varTemp, -->
<!--                                 Height = px(50))) -->
<!-- } -->
<!-- dplyr::tibble(` ` = rownames(DataSummary), DataSummary) %>% -->
<!--   gt() %>% -->
<!--   text_transform(locations = cells_body(columns = vars("Distribution"), rows = ! rownames(DataSummary) %in% c("n", "Predictors", "Outcomes", "")), -->
<!--                  fn = function(x) c(ContVarList_gg, CatVarList_gg, OutcVarList_gg)) %>% -->
<!--   tab_style(locations = cells_body(vars(!!sym(col_names[1])), rows = ! rownames(DataSummary) %in% c("Predictors", "Outcomes", "")), style = cell_text(color = ggplot2::scale_colour_brewer(palette = "Set1")$palette(9)[1])) %>% -->
<!--   # tab_style(locations = cells_body(vars(!!sym(col_names[1])), rows = ! rownames(DataSummary) %in% c("Predictors", "Outcomes", "")), style = cell_text(color = color_list[1])) %>% -->
<!--   tab_style(locations = cells_body(vars(!!sym(col_names[2])), rows = ! rownames(DataSummary) %in% c("Predictors", "Outcomes", "")), style = cell_text(color = ggplot2::scale_colour_brewer(palette = "Set1")$palette(9)[2])) %>% -->
<!--   tab_style(locations = cells_body(vars(!!sym(col_names[3])), rows = ! rownames(DataSummary) %in% c("Predictors", "Outcomes", "")), style = cell_text(color = ggplot2::scale_colour_brewer(palette = "Set1")$palette(9)[3])) %>% -->
<!--   fmt_missing(columns = vars("Distribution"), missing_text = "") -> gt_Fnl -->

<!-- gt_Fnl -->

<!-- ``` -->

### Two years, Bertens vs History - all COPD
```{r ROCTwo, echo=FALSE}

# for two year prediction
roc(predictor=eclipseComplete$predictedBertens, response = eclipseComplete$Observed_Exac_in2to3,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)  

#history alone for two years
roc(predictor=eclipseComplete$year1FreqExacerbator, response = eclipseComplete$Observed_Exac_in2to3,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)     
# for two year outcome
calibrate.plot(y = eclipseComplete$Observed_Exac_in2to3, p = eclipseComplete$predictedBertens)


dc_bertens_2yrs <- decision_curve(Observed_Exac_in2to3 ~ predictedBertens, data = eclipseComplete)
dc_history_2yrs <- decision_curve(Observed_Exac_in2to3 ~ year1FreqExacerbator, data = eclipseComplete)
plot_decision_curve(list(dc_bertens_2yrs, dc_history_2yrs),
                    curve.names = c("Bertens Model", "Exacerbation History"),
                    confidence.intervals = FALSE,  #remove confidence intervals
                    cost.benefit.axis = FALSE) #remove cost benefit axis)

```

<!-- ### Two years - Smokers -->

```{r ROCTwoSmokers, echo=FALSE, include=FALSE}

## smokers - 2 years
BertensROCSmokers2Yrs <- roc(predictor=eclipseCompleteSmokers$predictedBertens, response = eclipseCompleteSmokers$Observed_Exac_in2to3,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

HistoryROCSmokers2Yrs <- roc(predictor=eclipseCompleteSmokers$year1FreqExacerbator, response = eclipseCompleteSmokers$Observed_Exac_in2to3,
                             plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

Rocs <- list (Bertens = BertensROCSmokers2Yrs , History = HistoryROCSmokers2Yrs)
ggroc (Rocs, size = 1)  + theme_bw(base_size = 14) +
    theme(legend.title = element_blank()) + xlab ("Specificity") + 
    ylab("Sensitivity") 


# for two year outcome
calibrate.plot(y = eclipseCompleteSmokers$Observed_Exac_in2to3, p = eclipseCompleteSmokers$predictedBertens)


dc_bertens_2yrsSmokers <- decision_curve(Observed_Exac_in2to3 ~ predictedBertens, data = eclipseCompleteSmokers, fi)
dc_history_2yrsSmokers <- decision_curve(Observed_Exac_in2to3 ~ year1FreqExacerbator, data = eclipseCompleteSmokers)
plot_decision_curve(list(dc_bertens_2yrsSmokers, dc_history_2yrsSmokers),
                    curve.names = c("Bertens Model Smokers", "Exacerbation History Smokers"),
                    confidence.intervals = FALSE,  #remove confidence intervals
                    cost.benefit.axis = FALSE) #remove cost benefit axis)
##
```

### One year predicitons 

```{r ROCOne, echo=FALSE, cache=TRUE, include=TRUE}

# for 1 year prediction
roc(predictor=eclipseComplete$predictedBertens1Yr, response = eclipseComplete$Observed_Exac_in2,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

# for 1 year smokers only prediction 
roc(predictor=eclipseCompleteSmokers$predictedBertens1Yr, response = eclipseCompleteSmokers$Observed_Exac_in2,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          


#history alone for 1 year
roc(predictor=eclipseComplete$year1FreqExacerbator, response = eclipseComplete$Observed_Exac_in2,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          


# for one year outcome
calibrate.plot(y = eclipseComplete$Observed_Exac_in2, p = eclipseComplete$predictedBertens1Yr)

# net_benefit <- function (data, response, predictor, threshold) {
#   
# Calc <- eclipseComplete %>%
# mutate(predictedOutcome = ifelse(predictor>=threshold, 1, 0),
#                            truePos = ((predictedOutcome == 1) & (response==1)),
#                            falsePos = ((predictedOutcome == 1) & (response==0)))
# TPR <- Calc %>% summarise(count = sum(truePos)/n())
# message(TPR)
# FPR <- Calc %>% summarise(count = sum(falsePos)/n())
# message(FPR)
# 
# nb <- TPR - FPR * (threshold/(1-threshold))
# 
# return (nb)
# }
# 
# net_benefit(eclipseComplete, Observed_Exac_in2, predictedBertens1Yr, 0.40)

dc_bertens_1yr <- decision_curve(Observed_Exac_in2 ~ predictedBertens1Yr, data = eclipseComplete, fitted.risk = TRUE)
dc_history_1yr <- decision_curve(Observed_Exac_in2 ~ year1FreqExacerbator, data = eclipseComplete)
plot_decision_curve(list(dc_bertens_1yr, dc_history_1yr),
                    curve.names = c("Bertens 1Yr", "Exacerbation History"),
                    standardize = FALSE,
                    confidence.intervals = FALSE,  #remove confidence intervals
                    cost.benefit.axis = FALSE) #remove cost benefit axis)

# # one year Smokers
# dc_bertens_1yrSmokers <- decision_curve(Observed_Exac_in2 ~ predictedBertens1Yr, data = eclipseCompleteSmokers)
# dc_history_1yrSmokers <- decision_curve(Observed_Exac_in2 ~ year1FreqExacerbator, data = eclipseCompleteSmokers)
# plot_decision_curve(list(dc_bertens_1yrSmokers, dc_history_1yrSmokers),
#                     curve.names = c("Bertens 1Yr Smokers", "Exacerbation History Smokers"),
#                     confidence.intervals = FALSE,  #remove confidence intervals
#                     cost.benefit.axis = FALSE) #remove cost benefit axis)
```

```{r NumbersforManuscript, echo=FALSE, cache=TRUE, include=TRUE}

dc_bertens_data <- as_tibble (dc_bertens_1yr$derived.data) %>%
  mutate (NB_Bertens = NB) %>% select(thresholds, NB_Bertens)

dc_history_data <- as_tibble (dc_history_1yr$derived.data) %>%
  mutate (NB_history = NB) %>% select(thresholds, NB_history)

dc_data <- dc_bertens_data %>% inner_join(dc_history_data, by = "thresholds")

Calc <- eclipseComplete %>%
  mutate(BertensWillHaveExac = ifelse(predictedBertens1Yr>=0.40, 1, 0),
                           truePos = ((BertensWillHaveExac == 1) & (Observed_Exac_in2==1)),
                           falsePos = ((BertensWillHaveExac == 1) & (Observed_Exac_in2==0)))
Calc %>% summarise(count = sum(truePos)/n())
Calc %>% summarise(count = sum(falsePos)/n())


```


### ACCEPT Severe

```{r acceptSev, echo=FALSE, cache=TRUE}


## ACCEPT
#eclipseACCEPT <- readRDS("externalResultswithHx.rds")
eclipseACCEPT <- readRDS("externalResultsAllHx.rds") %>% 
  mutate(year1FreqExacerbator = ifelse(((obsExac_yr1>1) | (obsExac_severe_yr1>0)), 1, 0),
         hadSevereExac = ifelse(observedSevereExacCount>0, 1, 0),
         hadExac = ifelse(observedExacCount>0, 1, 0))

AcceptROCSev <- roc(predictor=eclipseACCEPT$predicted_severe_exac_probability_oldMethod, 
                    response = eclipseACCEPT$hadSevereExac,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

HistoryROCSev <- roc(predictor=eclipseACCEPT$year1FreqExacerbator, 
                     response = eclipseACCEPT$hadSevereExac,
                             plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

AcceptRocsSev <- list (acceptSev = AcceptROCSev , History = HistoryROCSev)
ggroc (AcceptRocsSev, size = 1)  + theme_bw(base_size = 14) +
    theme(legend.title = element_blank()) + xlab ("Specificity") + 
    ylab("Sensitivity") + labs(caption="For Severe Exacerbations")


calibrate.plot(y = eclipseACCEPT$hadSevereExac, p = eclipseACCEPT$predicted_severe_exac_probability_oldMethod)


dc_accept_sev <- decision_curve(hadSevereExac ~ predicted_severe_exac_probability_oldMethod, 
                                data = eclipseACCEPT, fitted.risk = TRUE)
dc_history_accept_sev <- decision_curve(hadSevereExac ~ year1FreqExacerbator, data = eclipseACCEPT)
plot_decision_curve(list(dc_accept_sev, dc_history_accept_sev),
                    curve.names = c("ACCEPT Severe", "Exacerbation History - Severe"),
                    confidence.intervals = FALSE,  #remove confidence intervals
                    cost.benefit.axis = FALSE) #remove cost benefit axis)


```

```{r acceptModSev, echo=FALSE, cache=TRUE}

AcceptROC <- roc(predictor=eclipseACCEPT$predicted_exac_probability, 
                 response = eclipseACCEPT$hadExac,
    plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

HistoryROC <- roc(predictor=eclipseACCEPT$year1FreqExacerbator, 
                  response = eclipseACCEPT$hadExac,
                             plot = T, ci=T, print.auc=TRUE,  boot.n=1000, ci.alpha=0.95, stratified=FALSE, show.thres=TRUE, grid=TRUE)                          

AcceptRocs <- list (accept = AcceptROC , History = HistoryROC)
ggroc (AcceptRocs, size = 1)  + theme_bw(base_size = 14) +
    theme(legend.title = element_blank()) + xlab ("Specificity") + 
    ylab("Sensitivity") + labs(caption="For Moderate and Severe Exacerbations")

calibrate.plot(y = eclipseACCEPT$hadExac, p = eclipseACCEPT$predicted_exac_probability)


dc_accept <- decision_curve(hadExac ~ predicted_exac_probability, 
                            data = eclipseACCEPT, fitted.risk = TRUE)


betterThanAllPoint <- as_tibble (dc_accept$derived.data) %>% 
  select (thresholds, NB, model) %>%
  pivot_wider(names_from = model, values_from = NB) %>%
  mutate(betterThanAll = `hadExac ~ predicted_exac_probability` > All)


dc_history_accept <- decision_curve(hadExac ~ year1FreqExacerbator, 
                                    data = eclipseACCEPT)
plot_decision_curve(list(dc_accept, dc_history_accept),
                    curve.names = c("ACCEPT", "Exacerbation History "),
                    confidence.intervals = FALSE,  #remove confidence intervals
                    standardize = FALSE,
                    cost.benefit.axis = FALSE) #remove cost benefit axis)


# Comparing ACCEPT vs 1 Year Bertens and History
plot_decision_curve(list(dc_accept, dc_history_1yr, dc_bertens_1yr),
                    curve.names = c("ACCEPT", "Exacerbation History ", "Bertens"),
                    confidence.intervals = FALSE,  #remove confidence intervals
                    cost.benefit.axis = FALSE) #remove cost benefit axis))

# 
# externalResults$hadExac2 <-ifelse(externalResults$observedExacCount>1, 1, 0)
# 
# dc_accept <- decision_curve(hadExac2 ~ predicted_exac_probability, data = externalResults)
# dc_history_accept <- decision_curve(hadExac2 ~ obsExac_yr1, data = externalResults)
# plot_decision_curve(list(dc_accept, dc_history_accept),
#                     curve.names = c("ACCEPT 2 or more", "Exacerbation History - 2 or more"),
#                     confidence.intervals = FALSE,  #remove confidence intervals
#                     cost.benefit.axis = FALSE) #remove cost benefit axis)
# 

```


```{r ACCEPTNumbersforManuscript, echo=FALSE, cache=TRUE, include=TRUE}

dc_accept_data <- as_tibble (dc_accept$derived.data) %>%
  mutate (NB_Bertens = NB) %>% select(thresholds, NB_Bertens)

dc_history_accept_data <- as_tibble (dc_history_accept$derived.data) %>%
  mutate (NB_history = NB) %>% select(thresholds, NB_history)

dc_data <- dc_accept_data %>% inner_join(dc_history_accept_data, by = "thresholds")

## 0.4 Threshold
ACCEPT0.4 <- eclipseACCEPT %>%
  mutate(ACCEPTWillHaveExac = ifelse(predicted_exac_probability>=0.40, 1, 0),
         truePos = ((ACCEPTWillHaveExac == 1) & (hadExac==1)),
         falsePos = ((ACCEPTWillHaveExac == 1) & (hadExac==0)),
         trueNeg = ((ACCEPTWillHaveExac == 0) & (hadExac==0)),
         falseNeg = ((ACCEPTWillHaveExac == 0) & (hadExac==1)))


## 2 by 2 Table for 0.4
message("For a threshold of 0.4")
ACCEPT0.4 %>% select(truePos, falsePos, trueNeg, falseNeg) %>% summarise(TP = sum(truePos),
                                                                    FP = sum(falsePos),
                                                                    TN = sum(trueNeg),
                                                                    FN = sum(falseNeg))
## TPR and FPR for 0.4
TPR0.4 <- ACCEPT0.4 %>% summarise(count = sum(truePos)/n())
message("TPR for 0.4 is ", as.numeric(TPR0.4))
FPR0.4 <- ACCEPT0.4 %>% summarise(count = sum(falsePos)/n())
message("FPR for 0.4 is", as.numeric(FPR0.4 ))


## 0.2 Threshold
ACCEPT0.2 <- eclipseACCEPT %>%
  mutate(ACCEPTWillHaveExac = ifelse(predicted_exac_probability>=0.20, 1, 0),
         truePos = ((ACCEPTWillHaveExac == 1) & (hadExac==1)),
         falsePos = ((ACCEPTWillHaveExac == 1) & (hadExac==0)),
         trueNeg = ((ACCEPTWillHaveExac == 0) & (hadExac==0)),
         falseNeg = ((ACCEPTWillHaveExac == 0) & (hadExac==1)))


## 2 by 2 Table for 0.4
message("For a threshold of 0.2")
ACCEPT0.2 %>% select(truePos, falsePos, trueNeg, falseNeg) %>% summarise(TP = sum(truePos),
                                                                    FP = sum(falsePos),
                                                                    TN = sum(trueNeg),
                                                                    FN = sum(falseNeg))
## TPR and FPR for 0.4
TPR0.2 <- ACCEPT0.2 %>% summarise(count = sum(truePos)/n())
message("TPR for 0.2 is ", as.numeric(TPR0.2))

FPR0.2 <- ACCEPT0.2 %>% summarise(count = sum(falsePos)/n())
message("FPR for 0.2 is ", as.numeric(FPR0.2))


```
